### ISSUE TITLE
searchbar

### ISSUE THREAD

**Issue by kyfike** [Countmooshroom/College-Reviews#2]
The search bar isn't functional yet.

**Comment by kyfike** [comment]
The searchbar works, but it won't search all the records. I have discovered which records are searchable by searching a blank space. ... Does it have to do with the fact that all the records aren't appearing in the Admin console for me?

My admin console Teacher records:
<img width="1440" alt="Screen Shot 2022-12-13 at 8 54 54 PM" src="https://user-images.githubusercontent.com/88905898/207502184-14cec5bf-8505-4011-a4d4-aba9880278bd.png">

Records that can be returned when I enter search parameters:
<img width="1440" alt="Screen Shot 2022-12-13 at 8 55 21 PM" src="https://user-images.githubusercontent.com/88905898/207502189-7c5cae98-f9b5-4ab9-987e-c8e083c95959.png">

All records that should return results:
<img width="1440" alt="Screen Shot 2022-12-13 at 8 56 49 PM" src="https://user-images.githubusercontent.com/88905898/207502194-c1ecec2d-f06f-4b7f-9802-a20512808e99.png">

**Comment by Countmooshroom** [comment]
The full list of teachers is pulled from the Choices table, but when you go to an individual teacher page, it has more information that is pulled from the Teachers table.  To solve this difference in data, I coded the database to automatically create a new teacher object and page when someone goes to that page for the first time.  However, it still does not create a Teacher object when a user creates a new teacher with the input app.
